trigger:  
  branches:    
    include:      
      - dev
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'docker-spn'
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: S3Upload@1
      inputs:
          awsCredentials: 'aws-spn'
          regionName: 'ap-south-1'
          bucketName: 'testing'
          globExpressions: '**'
          createBucket: true