trigger:  
  branches:    
    include:      
      - dev
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourceDirectory)/Dockerfile'
        repository: $(imageName)
        tags: |
          $(tag)
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'aws-spn'
        regionName: 'ap-south-1'
        imageSource: 'imageid'
        sourceImageId: '$(imageName):$(tag)'
        repositoryName: '$(repoName)'
        pushTag: '$(tag)'
        forceDockerNamingConventions: true