jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        aws configure set aws_access_key_id AKIAU3DSXSIYTQKEMCYC 
        aws configure set aws_secret_access_key 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
        aws configure set aws_default_region ap-south-1
        $password=aws ecr get-login-password --region ap-south-1 --profile default
        docker login --username AWS --password $password 333100585521.dkr.ecr.ap-south-1.amazonaws.com
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'docker build -t 333100585521.dkr.ecr.ap-south-1.amazonaws.com/test:latest .'
      workingDirectory: '$(System.DefaultWorkingDirectory)/frontend'
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'docker push 333100585521.dkr.ecr.ap-south-1.amazonaws.com/test:latest'