jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - task: AWSPowerShellModuleScript@1
    inputs:
      awsCredentials: 'aws-spn'
      regionName: 'ap-south-1'
      scriptType: 'inline'
      inlineScript: 'aws ecr get-login-password --region ap-south-1 --profile default | docker login --username AWS --password-stdin 333100585521.dkr.ecr.ap-south-1.amazonaws.com'
  # - task: Docker@2
  #   displayName: 'Build Docker Image'
  #   inputs:
  #     containerRegistry: 'dkr-spn'
  #     repository: '$(imageName)'
  #     command: 'build'
  #     Dockerfile: '**/Dockerfile'
  #     tags: 'dev'
  # - task: ECRPushImage@1
  #   inputs:
  #     awsCredentials: 'aws-spn'
  #     regionName: 'ap-south-1'
  #     imageSource: 'imagename'
  #     sourceImageName: '333100585521.dkr.ecr.ap-south-1.amazonaws.com/test'
  #     repositoryName: '$(repoName)'
