trigger:  
  branches:    
    include:      
      - dev
resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          aws configure set aws_access_key_id AKIAU3DSXSIYTQKEMCYC 
          aws configure set aws_secret_access_key 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
          aws configure set aws_default_region ap-south-1
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'docker build -t billpay .'
        workingDirectory: '$(System.DefaultWorkingDirectory)/frontend'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/frontend'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/billpay.zip'
        replaceExistingArchive: false

    - task: S3Upload@1
      inputs:
        awsCredentials: 'aws-spn'
        regionName: 'ap-south-1'
        bucketName: 'chudham'
        sourceFolder: '$(Build.ArtifactStagingDirectory)'
        globExpressions: '**'
        createBucket: true
    - task: BeanstalkDeployApplication@1
      inputs:
        awsCredentials: 'aws-spn'
        regionName: 'ap-south-1'
        applicationName: 'xnode-testing'
        environmentName: 'xnode-dev'
        applicationType: 's3'
        deploymentBundleBucket: 'chudham'
        deploymentBundleKey: 'your/bundle/key/in/s3.zip'

