trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'YourAzureSubscription'
  awsAccessKey: 'YourAWSAccessKey'    
  awsSecretKey: 'YourAWSSecretKey'
  ecrRepo: 'YourECRRepo'
  ebApplication: 'YourEBApplication'
  ebEnvironment: 'YourEBEnvironment'
  imageRepository: 'YourACRServiceConnection'
  tag: '$(Build.BuildNumber)'  # You can use a different tag if needed

steps:
- task: Docker@2
  displayName: 'Build and push image to ACR'
  inputs:
    containerRegistry: 'YourACRServiceConnection'
    repository: '$(imageRepository)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'
      
# - task: AmazonWebServices.aws-cli.AWSCLI@2
#   displayName: 'Login to AWS ECR'
#   inputs:
#     awsCredentials: 'YourAWSServiceConnection'
#     regionName: 'us-east-1'
#     command: 'ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin YourAWSAccount.dkr.ecr.us-east-1.amazonaws.com'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-spn'
    regionName: 'us-east-1'
    awsCommand: 'ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin YourAWSAccount.dkr.ecr.us-east-1.amazonaws.com'
 
# - task: Docker@2    
#   displayName: 'Tag image for ECR'
#   inputs:
#     containerRegistry: 'YourACRServiceConnection'
#     repository: '$(imageRepository)'
#     command: 'tag'
#     arguments: '--source $(imageRepository):$(tag) --target YourAWSAccount.dkr.ecr.us-east-1.amazonaws.com/$(ecrRepo):$(tag)'
    
- task: Docker@2
  displayName: 'Push image to ECR'    
  inputs:
    containerRegistry: 'YourACRServiceConnection'
    repository: 'YourAWSAccount.dkr.ecr.us-east-1.amazonaws.com/$(ecrRepo)'
    command: 'push'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-spn'
    regionName: 'us-east-1'
    awsCommand: 'eb deploy $(ebEnvironment) --label $(Build.BuildNumber)'
