# Variable 'imageName' was defined in the Variables tab
# Variable 'repoName' was defined in the Variables tab
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:

  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      containerRegistry: 'dkr-spn'
      repository: '$(imageName)'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'dev'
  - task: ECRPushImage@1
    inputs:
      awsCredentials: 'aws-spn'
      regionName: 'ap-south-1'
      imageSource: 'imageid'
      sourceImageId: '$(imageName):$(tag)'
      repositoryName: '$(repoName)'
      pushTag: '$(tag)'


