stages:
  - stage: build
    displayName: Build & Push Application
    pool:
      vmImage: 'ubuntu-latest'
variables:
  - name: ecrRepository
    value: 'xnode-container-registry'
  - name: ecrRegion
    value: 'us-east-1'
  - name: ebEnvironment
    value: 'xnode-dev'

stages:
- stage: Build
  jobs:
  - job: BuildAndPushImage
    steps:
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        containerfile: 'Dockerfile'
        buildContext: '.'

    - task: AWS.ECRPushImage@1
      displayName: Push Docker image to ECR
      inputs:
        awsCredentials: '$(System.DefaultWorkingDirectory)/aws-credentials.json'
        awsRegion: '$(ecrRegion)'
        repositoryName: '$(ecrRepository)'
        imageTag: '$(Build.BuildNumber)'

- stage: Deploy
  jobs:
  - job: DeployToEB
    steps:
    - task: AWS.ElasticBeanstalkDeployApplication@1
      displayName: Deploy application to Elastic Beanstalk
      inputs:
        awsCredentials: '$(System.DefaultWorkingDirectory)/aws-credentials.json'
        applicationName: 'xnode-application'
        environmentName: '$(ebEnvironment)'
        versionLabel: '$(Build.BuildNumber)'